name: Deploy React App to S3

on:
  push:
    branches:
      - main   # Trigger only when pushing to main branch

jobs:
  deploy:
    runs-on: windows-latest   # Changed from ubuntu-latest to windows-latest

    steps:
      # Step 1: Checkout your repository code
      - name: Checkout source code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js for React build
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '^19.1.1' # Make sure this matches your React project's version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the React app
      - name: Build project
        run: npm run build

      # Step 5: Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2 # Change to your AWS region

      # Step 6: Deploy to S3 bucket
      - name: Deploy to S3
        run: aws s3 sync build/ s3://travel-planner-bot --delete
